version: "3.7"
services:
  rockbot:
    container_name: rockbot
    image: intelligentdesigns/streamlit-plus:stbot-latest
    restart: unless-stopped
    volumes:
# Mount your own Streamlit project if you'd like to /app if you'd like. main.py will run automatically
      - $DOCKERDIR/rockbot/src:/app
    ports:
      - 8080:8080
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    environment:
      - V_MAX_CHARS = 8 # Edit to set default max chars as (V_MAX_CHARS-1)*64.  This can be resource intensive so adjust based on your CPU/GPU power. Max per this model is 9 (512 chars)
      - V_NSAMPLES = 5 # Edit to set max songs to generate. Adjust based on your CPU/GPU power
      - STREAMLIT_SERVER_PORT=8080 #This needs to match exposed port in Dockerfile. See https://github.com/bigjoedata/streamlit-plus for dockerfile
    # You may need to uncomment these for some use cases
    # - enableCORS=false
    # - enableXsrfProtection=false
      - TZ=$TZ
    command: streamlit run main.py
